import { LinkForm } from "./link-form";
import { LinksTable } from "./links-table";
import { LinkDTO } from "@/lib/links";

export function LinkDashboard({
  links,
  baseUrl,
}: {
  links: LinkDTO[];
  baseUrl: string;
}) {
  const totalClicks = links.reduce((acc, link) => acc + link.clickCount, 0);
  const lastActivity =
    links
      .map((link) => link.lastClicked ?? link.createdAt)
      .sort((a, b) => new Date(b).getTime() - new Date(a).getTime())[0] ?? null;

  return (
    <div className="space-y-10">
      <section className="grid gap-6 lg:grid-cols-[1.25fr,1fr]">
        <div className="rounded-3xl border border-white/10 bg-gradient-to-br from-indigo-600/30 via-indigo-900/50 to-slate-950 p-8 shadow-2xl shadow-indigo-950/40">
          <p className="mb-2 text-sm font-semibold uppercase tracking-widest text-indigo-200">
            TinyLink
          </p>
          <h1 className="text-3xl font-semibold text-white">Short links, big impact.</h1>
          <p className="mt-3 max-w-xl text-sm text-indigo-100/80">
            Create branded short URLs, share them anywhere, and monitor engagement in real time.
          </p>
          <div className="mt-6 rounded-2xl border border-white/10 bg-slate-950/60 p-6">
            <h2 className="text-base font-semibold text-white">Add a new link</h2>
            <p className="mb-4 text-sm text-slate-400">
              Generate an autogenerated code or provide your own slug.
            </p>
            <LinkForm baseUrl={baseUrl} />
          </div>
        </div>
        <div className="rounded-3xl border border-white/10 bg-slate-950/60 p-6 shadow-inner shadow-black/50">
          <div className="space-y-6">
            <StatsTile label="Total links" value={links.length.toString()} hint="+ custom codes" />
            <StatsTile
              label="Lifetime clicks"
              value={totalClicks.toLocaleString()}
              hint="302 redirects tracked"
            />
            <StatsTile
              label="Last activity"
              value={lastActivity ? new Date(lastActivity).toLocaleString() : "—"}
              hint="Based on click or creation time"
            />
          </div>
        </div>
      </section>

      <LinksTable links={links} baseUrl={baseUrl} />
    </div>
  );
}

function StatsTile({ label, value, hint }: { label: string; value: string; hint: string }) {
  return (
    <div className="rounded-2xl border border-white/5 bg-white/5 p-4">
      <p className="text-xs uppercase tracking-widest text-slate-400">{label}</p>
      <p className="mt-2 text-3xl font-semibold text-white">{value}</p>
      <p className="text-xs text-slate-400">{hint}</p>
    </div>
  );
}

